cabal-version:      2.4
name:               egraphs-modulo-theories
version:            0.1.0.0
license:            MIT
copyright:          2026 Sofia B.
maintainer:         sofia.ma@protonmail.com
author:             Sofia B.
synopsis:           E-graphs modulo theories
description:

  A thesis project

extra-source-files:
  LICENSE
  README.md

executable egraphs-modulo-theories
  mixins:
    base hiding (Prelude),
    relude (Relude as Prelude),
    relude

  build-depends:
    , array
    , assoc
    , base
    , bifunctors
    , bytestring
    , comonad
    -- , comonad-extras -- version issue
    , containers
    , criterion
    , data-fix
    , deriving-compat
    , deepseq
    , free
    -- , functor-combinators
    , graphviz
    , hashable
    , lens
    , megaparsec
    , monoidal-containers
    , mtl
    , optparse-applicative
    , parser-combinators
    , prettyprinter
    , prettyprinter-ansi-terminal
    , profunctors
    , QuickCheck
    , recursion-schemes
    , relude
    , semialign
    , semigroupoids
    -- , smash -- bug: won't build for base ≥ 4.17
    , tagged
    , text
    , these
    , transformers
    , unordered-containers
    , witherable

  ghc-options:
    -Wall -Wincomplete-record-updates -Wincomplete-uni-patterns

  default-extensions:
    ApplicativeDo
    BangPatterns
    BinaryLiterals
    BlockArguments
    ConstrainedClassMethods
    ConstraintKinds
    DataKinds
    DefaultSignatures
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    EmptyCase
    EmptyDataDecls
    EmptyDataDeriving
    ExistentialQuantification
    ExplicitForAll
    ExplicitNamespaces
    FlexibleInstances
    FlexibleContexts
    FunctionalDependencies
    GADTs
    GeneralisedNewtypeDeriving
    -- HexFloatLiterals
    ImportQualifiedPost
    InstanceSigs
    KindSignatures
    LambdaCase
    LiberalTypeSynonyms
    MonadComprehensions
    NoMonomorphismRestriction
    MultiParamTypeClasses
    MultiWayIf
    NegativeLiterals
    NumDecimals
    NumericUnderscores
    OverloadedLists
    OverloadedStrings
    ParallelListComp
    PartialTypeSignatures
    PatternGuards
    PatternSynonyms
    PolyKinds
    RankNTypes
    ScopedTypeVariables
    StandaloneDeriving
    NoStarIsType
    TupleSections
    TypeApplications
    TypeFamilies
    TypeFamilyDependencies
    TypeOperators
    UnicodeSyntax
    ViewPatterns

  main-is:            Main.hs
  other-modules:      Lude, Egraph, Ematch, TermIndex, Examples, Signature
  hs-source-dirs:     app
  default-language:   Haskell2010
